var l,p=["127.0.0.1:1001","0.1.0.1:1001"],aa=/(http:\/\/www|https:\/\/secure)\.internetdownloadmanager\.com\/(autoreg|fillregform)\.html\?d=/,ba=/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/,ca=/\.([^.\\/]*?)(?=(?:\.[0-9]+)*)$/,da=["object","xmlhttprequest","other"],ea=[301,302,303,307],r=["http://*/*","https://*/*"],fa={16:1,17:2,18:4,45:8,46:16},ga={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},ha={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP",
"text/plain":"TXT","text/xml":"XML|F4M","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX","application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-gtar":"TAR",
"application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP","application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP",
"video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/flv":"FLV","video/mp2t":"TS","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV","video/webm":"WEBM","video/x-mp4":"MP4|M4V","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","video/x-flash-video":"FLV","video/x-flv":"FLV","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4",
"audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR","image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};function u(){this.b=this.constructor.prototype.d++}u.prototype.d=1;
function w(a,b,c,d){this.id=a;this.port=b;this.b=c;this.url=d}w.prototype.a=0;function ia(a,b,c){this.id=a;this.h=b||null;this.url=null;this.o=c}
function x(a,b,c,d,e,f){if(a){c=["MSG#",a,"#",b,"#",c,"#",d];this.d=a;this.type=b;this.e=d;this.a=e||[];this.f=c;if(e)for(a=0;a<e.length;a++)c.push(":",e[a]||0);if(f)for(var g in f)if(e=f[g],null!=e)if(c.push(",",g,"="),"number"==typeof e)c.push(e);else{b=a=e.length;for(d=0;d<b;){var h=e.charCodeAt(d++);128<=h&&(2048<=h?(a+=2,h-55296&56320||d++):a++)}c.push(a,":",e)}}else this.c=new FileReader}function ja(a){a.I||(a.f.push(";"),a.I=!0);return new Blob(a.f)}
function y(a,b,c){a.I?a.l(a):(b.a=c||0,b.b=0,a.c.onload=a.Ea.bind(a,b),z(a,b,0,50))}l=x.prototype;
l.Ea=function(a){for(var b=this.c.result;;)switch(a.b){case 0:var c=b.split(",",2),d=c.shift().split(":",2),e=d.shift();if(!d.length){if(!c.length)return this.l(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.l(this);this.d=parseInt(d[1]);this.type=parseInt(d[2]);this.e=parseInt(d[4]);b=b.slice(f);a.a+=f;a.b++;break;case 1:d=b.split(",",2);e=d.shift();if(!d.length){d=b.split(";",2);if(2>d.length)return z(this,a,b.length,100);a.b=4}f=e.length+1;this.a=d=e.split(":");
for(e=0;e<d.length;e++)c=d[e],d[e]=0>c.indexOf(".")?parseInt(c):parseFloat(c);b=b.slice(f);a.a+=f;a.b++;break;case 2:c=b.split(",",2);2>c.length&&(c=b.split(";",2));var d=c.shift().split(":",2),g=d.shift(),f=g.length,e=!1;if(d.length)f++;else{if(!c.length)return z(this,a,b.length,25);e=!0}d=g.split("=",3);if(2!=d.length)return this.l(this);c=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[c]=d;b=b.slice(f);a.b++;break}a.d=c;a.c=d;b=a.c;f=a.a;a=a.slice(f,f+b);a.size==b?this.c.readAsText(a):
this.l(this);return;case 3:return this[a.d]=b,a.a+=a.c,a.b++,z(this,a,0,21);case 4:switch(b[0]){case ",":a.b=2;b=b.slice(1);break;case ";":a.b++;break;default:return this.l(this)}a.a++;break;case 5:this.I=!0;this.B(this);a.size>a.a&&(b=new x,b.B=this.B,b.l=this.l,y(b,a,a.a));return}};function z(a,b,c,d){var e=b.a;c=e+c;b.size>c?a.c.readAsBinaryString(b.slice(e,c+d)):a.l(a)}l.g=null;l.B=null;l.l=null;l.I=!1;
function A(){var a=this.constructor.prototype,b;for(b in a)this[b]=a[b].bind(this);b=navigator.userAgent;a=b.match(/(\b(?!(?:Safari|Chrome)\/)\w+\/[\d\.]+\b)[^()]*$/);if(b=b.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/))this.Y=b[1]<<24|b[2]<<22|b[3]<<8|b[4],this.wa=b[0],this.ta=a?a[1]:b[0],this.pa=[],this.G=!1,this.b={},this.j={},this.a={},this.c={},this.h={},this.d={},this.e={},this.s={},this.S="",this.T=!0,this.ra=this.xa=1,this.f=null,this.N=1,this.t=!1,this.v=this.M=0,this.oa=null,this.Q=this.ma=
!1,this.va=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_link"),contexts:["link"],onclick:this.ya,enabled:!1}),this.ua=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_all"),contexts:["page"],onclick:this.$,enabled:!1}),this.qa=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_selected"),contexts:["selection"],onclick:this.$,enabled:!1}),this.n=[this.va,this.ua,this.qa],chrome.windows.onCreated.addListener(this.ha),chrome.windows.onRemoved.addListener(this.ia),
chrome.windows.onFocusChanged.addListener(this.Pa),chrome.tabs.onActivated.addListener(this.Ka),chrome.tabs.onUpdated.addListener(this.Ma),chrome.tabs.onAttached.addListener(this.La),this.K(),chrome.windows.getAll(null,this.Ba)}function B(a,b,c,d,e){var f=a.d[b];return f?f:a.d[b]=new w(b,c,d,e)}function C(a,b){var c=a.h[b];c&&delete a.h[b];return c}l=A.prototype;
l.K=function(){var a=new WebSocket("ws://"+p[this.M%p.length]+"/?cid="+Math.random().toString().substr(2,9),"plugin.v3.internetdownloadmanager.com");this.Z=a;a.onopen=this.da;a.onclose=this.O;a.onmessage=this.Ja;1==a.readyState?this.da():3==a.readyState&&this.O()};l.da=function(){this.t=!0;this.ra=1;var a={};a[112]=this.ta;a[113]=this.wa;a[114]="Chrome_RenderWidgetHostHWND";D(this,2,0,[3,1,7,0],a)};
l.O=function(){this.Z=null;if(this.t){this.t=!1;this.s={};for(var a;a=this.pa.shift();){var b=a.shift();b.removeListener.apply(b,a)}for(a=0;a<this.n.length;a++)chrome.contextMenus.update(this.n[a],{enabled:!1});this.G=!1}a=++this.M;b=p.length;10>a/b&&(a==b&&this.T&&this.J(),!a||a%b?this.K():window.setTimeout(this.K,15E3))};l.Ja=function(a){var b=new x;b.B=this.Ga;b.l=this.O;y(b,a.data)};
function D(a,b,c,d,e){if(!a.t)return!1;var f=a.ra++;b=new x(f,b,1,c,d,e);a.Z.send(ja(b));c&1&&(a.s[f]=b);return!0}
function E(a,b){var c=a.e;if(b.a){var d=b.a[6],e=d&&c[d];if(e){var f=e.type;return!f||"image"==f||e.C?(b.g=e.port.id,b.h=d,!0):!1}}var g=a.a,h=a.d,k=b[6],m=b[17],n=b[50],v=b[7],s,q;for(d in c){var e=c[d],t=e.url;if(t){if(t==k||t==m)if(f=e.type,!f||"image"==f||e.C)return b.g=e.port.id,b.h=parseInt(d),!0;t==n&&(q=e.port.id)}}for(d in h)if(c=h[d],t=c.url){if(t==k||t==m||t==n)if(e=c.port,v&&(f=g[e.tabId])&&f.url!=v&&(e=null),e)return b.g=e.id,!0;t==v&&(s=c.port.id)}return q||s?(b.g=q||s,!0):!1}
l.aa=function(a,b,c){if(c)return(c=(b=c.shift())&&this.a[b.id])?a.g=c.id:null;if(a.g)return a.g;if(a.a){var d=a.a[7];if(d&&this.j[d])return a.g=d}if(E(this,a))return a.g;var e=this.j,f=a[50],g=a[7];for(d in e){c=e[d];if(c.url==f){a.g=d;break}a.g||c.url!=g||(a.g=d)}if(a.g)return a.g;g&&chrome.tabs.query({url:g},F(this,a,b))};
l.L=function(a,b,c){if(void 0===b)0<a.tabId&&(a.a||!a.url?a.postMessage([11,a.tabId,null,null,!a.url]):chrome.webNavigation.getAllFrames({tabId:a.tabId},F(this,a,!0)));else if(c)for(b=c.length-1;0<=b;b--){var d=c[b];if(!d.Ra&&d.url==a.url){c=a.tabId;b=d.frameId;d=d.parentFrameId;if(0<b){var e=c+"."+b;this.a[e]=a;a.frameId=b;a.j=e}0<=d&&(a.d=d?c+"."+d:c);if(e=this.a[c])if(e=e.b[b]){var f=e.o,d=e.h;f&&a.url!=f&&(a.o=f);0<=d&&null==a.d&&(a.d=d?c+"."+d:c)}a.postMessage([11,c,b,d,!1]);break}}};
l.U=function(a,b,c,d){var e=G(a,!0);if(!e)return 0;if(1==e&&void 0===d)return chrome.cookies.getAll({url:a},F(this,a,b,c)),-1;"object"==typeof d&&(d=H(d));var e=[e],f={};f[6]=a;f[8]=c;f[51]=d;f[54]=navigator.userAgent;f[7]=b;D(this,14,0,e,f);return 3};
l.na=function(a,b,c,d,e){if(!d){if(!a||!a.length)return;c||(c={});var f=new I(this,a,b,c,!0);c.sa&&!c.ka&&chrome.cookies.getAll({url:c.sa},J(f,4));for(var g=0;g<a.length;g++)chrome.cookies.getAll({url:a[g][0]},J(f,g+5));if(f.c())return}e&&(c.ka=H(e));for(g=0;g<a.length;g++)a[g][4]=H(arguments[g+5]);var f=0,g=[a.length],h={8:4};h[54]=navigator.userAgent;h[7]=c.sa;h[110]=c.p;h[111]=c.ka;1<a.length&&(D(this,15,f,g,h),f=16,h={});for(var g=[0],k;k=a.shift();)h[6]=k[0],h[102]=k[2],h[50]=k[3],h[51]=k[4],
D(this,14,f,g,h)};function K(a,b,c,d){(b=b[c])?(b=d?b.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"):b.replace(/\?/g,".").replace(/\*/g,".*"),b="^(?:"+b+")$"):b="(?!)";a.b[c]=new RegExp(b,"i")}
function L(a,b,c,d,e,f,g,h){if(!d||a.b[-8]){var k=a.a[b];if(k){var m;m=new u;m=a.h[m.b]=m;var n=m.b;m.tabId=b;m.port=k;m.j=c;m.c=0;m.n=[];if(k=d&&!!e)m.v=!0,m.s=e,m.f=f,m.h=g,m.zoom=h,e.a||M(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.b[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d,e+=")(?::\\d+)?(?:\\W|$)");m.e=N(a,b,[12,n,c,k,e]);m.t=0;m.e||C(a,n)}}}
function O(a,b){if(b.Da)return a.sendRequest(b,6),1;var c=b.D,d=b.statusCode,e=b.C;if(!e&&!a.b[-9]||!c&&200!=d&&206!=d)return 1;var f=P(b.responseHeaders,"Content-Type"),g=P(b.responseHeaders,"Content-Disposition"),h=Q(f).toLowerCase(),d="attachment"==Q(g).toLowerCase();if(!c&&!d&&"text/html"==h)return 1;var k=b.url,f=R(g,"filename")||R(f,"name"),m=!1,g=!1;f?m=g=!0:f=S(k);var n=T(f).toUpperCase(),v=c,s=!1;if(!c){if(!m){var q=ha[h];if(q)if(q=q.split("|"),n&&0<=q.indexOf(n))m=!0;else if(e||!n)n=q.shift(),
m=!0;if(!n)if(e&&(q=P(b.responseHeaders,"Server"))&&"gvs"==q.toLowerCase().split(" ",1).shift()&&"videoplayback"==f)s=!0;else return 1;!n||m||!d&&h&&a.b[10].test(h)}if(e&&"ASF"==n){if((h=P(b.responseHeaders,"Content-Length"))&&102400>=parseInt(h))return 1;q=P(b.responseHeaders,"Server");if("DCLK-AdSvr"==q)return 1}e&&a.b[3].test(n)?s=!0:a.b[1].test(n)&&(v=e?!(a.b[-4]||a.b[4].test(n)):!0)}if(!v&&!s)return 1;h=s?a.b[11]:c?null:a.b[9];k=new URL(k);if(h&&h.test(k.hostname))return 1;c=c?2052:s?256:(e?
4096:0)|(g||d?16:8);"quic"==P(b.responseHeaders,"Client-Protocol")&&(c|=2097152);b.Aa=n;b.fileName=g?f:null;return a.sendRequest(b,v?2:4,c)?v?3:2:0}
l.sendRequest=function(a,b,c){var d=a.requestHeaders,e=a.responseHeaders,f=a.ja,g=parseInt(a.requestId),h=a.port&&a.port.id,k=a.timeStamp;"POST"==a.method&&(c|=512);var m=4>b?1:0;b=[g,h,Math.floor(k/1E3),Math.floor(k%1E3*1E3),a.R&31,b];g={};g[6]=U(a.url);g[17]=a.o;g[4]=a.Aa;g[100]=a.fileName;g[8]=c;g[11]=V(d);g[13]=V(e);g[18]=V(f);a.H&&(g[14]=ka(a.H,P(d,"Content-Type")));a.P&&(g[19]=ka(a.P,P(f,"Content-Type")));if(a=this.a[a.tabId])g[7]=a.url,g[110]=a.title;return D(this,13,m,b,g)};
function W(a,b){delete a.e[b]}l.r=function(a,b,c){if(4294967295==a)this.f=null,c=!0;else{var d=this.d[a];if(d){c=d.a;if(!c)return;if(b)switch(c){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.r.bind(null,a,!1,!0),1E3);return}d.a=0;c=!0}}c&&D(this,8,32,[a])};
function X(a,b,c,d){var e=a.d[b],f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var g,h,k,m,n;c&&(g=c.left,h=c.top,k=c.right||g+1,m=c.bottom||h+1,n=c.zoom,c=e.port.c)&&(g+=c.left,h+=c.top,k=Math.min(k+c.left,c.right),m=Math.min(m+c.top,c.bottom));D(a,9,f,[b,g,h,k,m,n])}
l.w=function(a){var b=this.c,c=[];if(a)(a=b[a])&&(a.m||a.q||c.push(a.i));else for(var d in b)a=b[d],a.m||a.q||c.push(a.i);if(c.length){b=[15,null,null];a={};var e=this.d;for(d in e){var f=e[d];f.a&&0<=c.indexOf(f.port.tabId)&&(f.b?(f=f.port,f.a||M(this,f,null,a),b[2]=d,f.postMessage(b)):X(this,d,null,!0))}}};function Y(a,b,c){if((b=a.c[b])&&!b.q){b=b.i;var d=c?0:2;c=c?32:64;var e=a.d,f;for(f in e){var g=e[f];g.a&&g.port.tabId==b&&g.a!=d&&(g.a=d,D(a,8,c,[f]))}}}
function Z(a,b,c,d){var e=a.v,f=(e&b)!=((c?63:32)&b);a.v=c?e|=b:e&=~b;f&&(c=a.b[-1],b=a.b[-2],c=a.ma=0!=c&&(e&c)==c,e=a.Q=0!=b&&(e&b)==b,a.oa=(c||e)&&d||null)}l.Qa=function(a,b){var c=this.c[a];c&&(c.q=null,b&&(chrome.windows.get(a,null,this.A),chrome.tabs.query({windowId:a,active:!0},this.A)),this.w(a))};
l.A=function(a){a instanceof Array&&(a=a.shift());if(a&&(!a.url||"chrome:"!=a.url.substr(0,7))){var b=a.windowId||a.id,c=this.c[b];if(c){if(a.windowId)c.i=a.id,a.width&&(c.W=a.width),a.height&&(c.V=a.height);else{var d="fullscreen"==a.state,e=d!=c.m;c.width=a.width;c.height=a.height;c.left=a.left;c.top=a.top;c.Ca="maximized"==a.state;c.m="fullscreen"==a.state;e&&(d?Y(this,b):this.w(b))}a=c.scale;d=(c.width-c.W)/2;e=c.height-c.V-d;c.border=Math.round(d*a);150>=e&&(c.X=Math.round(e*a));(c=this.c[b])&&
c.F&&(a=c.border,d=c.scale,D(this,7,0,[b,a,c.X,Math.round(c.width*d)-a,Math.round(c.height*d)-a]))}}};function M(a,b,c,d){a=a.a;c=[16,c];for(var e=[b],f;f=a[b.d];b=f){if(d)if(d[b.id])break;else d[b.id]=!0;e.push(f)}for(f=e.pop();b=e.pop();f=b)d=b.za,c[2]=d,c[3]=b.frameId,c[4]=d?null:b.url,c[5]=d?null:b.o,f.postMessage(c)}function N(a,b,c){a=a.a;var d=0,e;for(e in a)parseInt(e)==b&&(a[e].postMessage(c),d++);return d}
l.u=function(a){var b={file:"content.js",runAt:"document_start",allFrames:!0};620756992<this.Y&&(b.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{chrome.tabs.executeScript(a.shift().id,b)}catch(c){}else try{chrome.tabs.executeScript(a.id||a,b)}catch(d){}};function la(a,b){var c=a.c[b];c&&null==c.F&&D(a,6,17,[b,0,c.width,c.height,c.left,c.top,c.scale])}l.Ba=function(a){for(;a.length;)this.ha(a.shift(),!0)};l.ya=function(a){this.U(a.linkUrl,a.pageUrl,4)};
l.$=function(a,b){L(this,b.id,a.menuItemId==this.qa)};l.Ha=function(a){var b=a.sender.tab;if(b){var c=a.n||this.xa++,d=b.id,e="top"==a.name;a.id=c;a.tabId=d;a.windowId=b.windowId;a.e=!0;a.f=!1;a.a=e;a.frameId=e?0:null;a.j=e?d:null;a.url=a.sender.url||e&&b.url||null;a.o=null;e&&(a.b={});this.j[c]=a;e&&(this.a[d]=a);a.onMessage.addListener(this.Ia.bind(this,a));a.onDisconnect.addListener(this.ca);this.L(a)}};
l.ca=function(a){if(a.e){a.e=!1;var b=this.d,c=this.e,d=this.h,e;for(e in b)b[e].port===a&&(b[e].a&&this.r(e),delete b[e]);for(e in c)c[e].port===a&&delete c[e];for(e in d)d[e].port===a&&delete d[e];delete this.a[a.j];delete this.j[a.id];this.oa===a&&Z(this,63,!1)}};
l.Ia=function(a,b){switch(b[0]){case 21:var c=b[1];c&&(a.url=c,null==a.frameId&&this.L(a));break;case 22:var d=this.a,e=d[a.tabId+"."+b[2]],c=b[4];e.za=b[3];e.c=c;if(d=d[e.h])if(d=d.c)c.left+=d.left,c.top+=d.top,c.right=Math.min(c.right+d.left,d.right),c.bottom=Math.min(c.bottom+d.top,d.bottom);break;case 23:var c=a.windowId,f=a.tabId,g=b[1],d=b[2],e=b[4],h=this.c[c];if(g){if(g=C(this,g)){var h=f==h.i&&!h.m,k=!d||!e;k&&(d=f);if(f=b[7])g.a&&g.p&&g.a!=g.p||(g.a=f),g.p=f;var m=B(this,d,a,k?null:b[5],
k?null:b[6]),n=h&&!m.a;m.a=h?1:2;g instanceof x&&$(this,g,2,(h?128:64)|(k?512:0),c,d,f);k||(X(this,d,e),n&&window.setTimeout(this.w.bind(null,c),3E3))}}else b[3]?(this.r(d,!0),delete this.d[d]):e&&f==h.i&&!h.m&&X(this,d,e,!0);break;case 24:c=b[2];(d=this.h[b[1]])&&c&&(d.a&&d.p&&d.a!=d.p||(d.a=c),d.p=c);break;case 25:B(this,b[1],a,b[2],b[3]);break;case 26:L(this,a.tabId,!0,!0,a,b[1],b[2],b[3]);break;case 27:if(c=this.h[b[1]]){d=c.n;if(e=b[4])if("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array){if(g=
b[5])for(h=0;h<e.length;h++)e[h][3]=g;Array.prototype.push.apply(d,e)}b[3]&&(c.c+=b[3]);b[6]&&(c.pageUrl=b[6]);b[7]&&(c.p=b[7]);++c.t<c.e||(C(this,c.b),c.v?(d=this.c[c.port.windowId])&&d.i==c.tabId&&c.c&&(c.frame=c.s.c,e=c.zoom,D(this,10,0,[4294967295,d.id,Math.round(c.f*e)+d.border,Math.round(c.h*e)+d.X,0,c.c]),this.f=c.tabId,N(this,c.tabId,[13,!0])):d.length?this.na(d,c.j,c.G):window.alert(chrome.i18n.getMessage("cannot_find_links")))}break;case 28:this.r(4294967295);break;case 29:ma(this,a.windowId,
a.tabId);break;case 30:ma(this,a.windowId,a.tabId,b[1],b[2]);break;case 31:(c=fa[b[1]])&&Z(this,c,b[2],a);break;case 32:0==b[1]&&Z(this,32,b[2],a);break;case 33:Z(this,63,!1)}};
l.Ga=function(a){var b=a.type,c=a.e,d=a.a,e;if(1==b){var f=d[0];if(e=this.s[f])b=e.type,delete this.s[f]}switch(b){case 3:this.M=-1;this.S=a[13]||"m"+d[2];if(c=d[4]){c=c/96;a=this.Y;this.N=620756992>a?1:620756992<a&&621284967>a?c:637534208<a&&638078312>a?c:1.25<c?c:1;c=this.c;a=this.N;for(var g in c)d=c[g],d=[g,d.F,d.width,d.height,d.left,d.top,d.scale=a],D(this,6,17,d)}this.T&&this.J();break;case 4:g=this.b;g[-9]=0<(c&64);g[-8]=0<(c&32);g[-4]=0<(c&2);g[-1]=d[0];g[-2]=d[1];g[12]=a[12];K(this,a,1);
K(this,a,2);K(this,a,3);K(this,a,4);K(this,a,10);K(this,a,9,!0);K(this,a,11,!0);if(g=a[13])this.S=g;if(!this.G){this.G=!0;this.k(chrome.extension.onConnect,this.Ha);this.k(chrome.webNavigation.onCommitted,this.ba);this.k(chrome.webNavigation.onHistoryStateUpdated,this.Fa);this.k(chrome.webRequest.onBeforeRequest,this.ea,{urls:["http://*/*"],types:["main_frame","sub_frame"]},["blocking"]);this.k(chrome.webRequest.onBeforeRequest,this.ea,{urls:["https://*/*"],types:["main_frame","sub_frame"]},["blocking",
"requestBody"]);this.k(chrome.webRequest.onBeforeSendHeaders,this.fa,{urls:["http://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["requestHeaders"]);this.k(chrome.webRequest.onBeforeSendHeaders,this.fa,{urls:["https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","requestHeaders"]);this.k(chrome.webRequest.onHeadersReceived,this.ga,{urls:["http://*/*"],types:["object","image","xmlhttprequest","other"]},["responseHeaders"]);
this.k(chrome.webRequest.onHeadersReceived,this.ga,{urls:["https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","responseHeaders"]);this.k(chrome.webRequest.onResponseStarted,this.Oa,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});this.k(chrome.webRequest.onErrorOccurred,this.Na,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});for(g=0;g<this.n.length;g++)chrome.contextMenus.update(this.n[g],
{enabled:!0});chrome.tabs.query({url:r[0]},this.u);chrome.tabs.query({url:r[1]},this.u)}break;case 5:g=d[0];(a=this.c[g])?(c=0!=(c&128),a.m!=c&&(a.m=c)&&Y(this,g)):this.ia(g);break;case 6:g=e.a[0];c=d[1];if(g=this.c[g])g.F=c;break;case 8:g=d[0];c=c&32;if(4294967295==g)N(this,this.f,[13,!1]),this.f=null;else if(g=this.d[g])g.a=c?0:2;break;case 11:g=d[0];4294967295==g&&(L(this,this.f,!0,!0),this.f=null);break;case 12:try{var h=a.a[5],k=a[4];g=4==h?2:3;if((1==h||2==h)&&E(this,a)){if(this.b[3].test(k))1==
h?g=4:h=4;else if(this.b[-4]||this.b[4].test(k))g=4;a[8]|=256}if(4==h){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.la(a)}else $(this,a,g)}catch(m){$(this,a,0)}break;case 1:break;default:!e&&c&1&&D(this,1,0,[a.d,0,0,0])}};
l.la=function(a,b,c){try{if(!a.g)if(!b){var d=new I(this,a,!0);this.aa(a,d)||chrome.windows.getLastFocused(null,J(d,2));if(d.c())return}else if(c){var e=this.c[c.id],f=this.a[e&&e.i];f&&(a.g=f.id)}f=this.j[a.g];if(!f)return $(this,a,0);var g;var h=a.b;h||(h=u.prototype.d++,a.b=h,this.h[h]=a);g=h;if(!f.a){var k=this.a[f.tabId];k&&k.postMessage([14,g])}var m=[15,g,null,a[6],a[17],a[50],a[31]];f.a||M(this,f,g);f.postMessage(m)}catch(n){$(this,a,0)}};
function $(a,b,c,d,e,f,g){-1!=c&&(e=[b.d,c,e,f],f={},f[8]=b[8],g&&(f[110]=g),D(a,1,d|(0==c?4:2),e,f))}l.ba=function(a,b){var c=a.tabId,d=a.frameId;0<d&&(d=c+"."+d);!(d=this.a[d||c])||b&&a.url==d.url||(d.disconnect(),this.ca(d),this.u(c))};l.Fa=function(a){return this.ba(a,!0)};
l.ha=function(a,b){var c=a.id;this.c[c]={id:c,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.N,border:8,X:73,Ca:"maximized"==a.state,m:"fullscreen"==a.state,V:0,W:0,i:0,F:null,q:null};chrome.tabs.query({windowId:c,active:!0},this.A);chrome.tabs.query({windowId:c,url:r[0]},this.u);chrome.tabs.query({windowId:c,url:r[1]},this.u);b&&la(this,c)};l.ia=function(a){D(this,5,32,[a]);delete this.c[a]};l.Pa=function(a){la(this,a)};
l.Ma=function(a,b,c){var d=c.windowId,e=this.c[d];e&&!e.i&&this.A(c);"complete"==b.status&&(a=this.a[a])&&!a.f&&(a.f=!0,this.w(d))};l.Ka=function(a){this.v=0;this.f&&this.r(4294967295);var b=a.windowId;a=a.tabId;var c=this.c[b];c&&(Y(this,b),c.i=a,chrome.tabs.get(a,this.A),this.w(b))};l.La=function(a,b){var c=b.Sa,d=this.j,e;for(e in d)(port=d[e])&&port.tabId==a&&(port.windowId=c);Y(this,c,!0)};
function ma(a,b,c,d,e){a.f&&a.r(4294967295);var f=a.c[b];f&&f.i==c&&(d&&(f.W=d),e&&(f.V=e),Y(a,b),f.q&&window.clearTimeout(f.q),f.q=window.setTimeout(a.Qa.bind(null,b,d||e),250))}
l.ea=function(a){var b=a.tabId;if(!(0>b)){var c=a.url,d=G(c);if(aa.test(c))return a=this.a[b],this.U("idmreg"+c.substr(c.indexOf(":")),a&&a.url),{redirectUrl:chrome.extension.getURL("captured.html")};if("sub_frame"==a.type){var b=this.a[b],e=a.frameId;b&&0<e&&!b.b[e]&&(b.b[e]=new ia(e,a.parentFrameId,c))}if(!this.Q&&d&128&&"POST"==a.method&&a.requestBody){c=a.requestId;d=a.requestBody;if(b=d.raw)for(e=0;e<b.length&&(b[e].bytes||(b=null));e++);if(b||d.formData)(b=this.e[c])?b.requestBody=d:this.e[c]=
a}}};
l.fa=function(a){var b=a.tabId;if(0<b){var c=a.requestId,d=a.url,e=a.method,f=G(d);if(!f||"GET"!=e&&"POST"!=e)return W(this,c);a.D=this.ma;a.a=this.Q;var g=this.e[c];g&&(a.port=g.port,a.H=g.requestBody,g.R&&(a.o=g.o||g.url,a.ja=g.ja||g.requestHeaders,a.P=g.P||g.H,a.D=g.D,a.a=g.a));var g=a.D,h=a.type,k="main_frame"==h||"sub_frame"==h;if(!a.port){var m=0<a.frameId?b+"."+a.frameId:0;if(!(a.port=m&&this.a[m]||this.a[b])&&!k)return W(this,c)}if("POST"==e&&f&128&&!a.H||!g&&k&&0>d.indexOf("?")&&(b=S(d),
(b=T(b).toUpperCase())&&this.b[2].test(b)))return W(this,c);0<=d.indexOf("#")&&(a.url=U(d));a.R=f;a.C=0<=da.indexOf(h);this.e[c]=a;if(g&&f&128&&3==O(this,a))return{cancel:!0}}};
l.ga=function(a){var b=a.requestId,c=this.e[b];if(c){if("image"==c.type){var d=P(a.responseHeaders,"Content-Type");if(d&&"image/"==d.substr(0,6).toLowerCase())return W(this,b)}b=c.statusCode=parseInt(a.statusLine.split(" ",2).pop());if((c.Da=0<=ea.indexOf(b))||!c.a)if(c.R&128||"quic"==P(a.responseHeaders,"Client-Protocol"))if(c.statusLine=a.statusLine,c.responseHeaders=a.responseHeaders,3==O(this,c))return{responseHeaders:[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},
{name:"Content-Length",value:"0"}]}}};l.Oa=function(a){a=a.requestId;var b=this.e[a];if(b){if("sub_frame"==b.type){var c=this.a[b.tabId];if(c=c&&c.b[b.frameId])c.url=b.url}b.C?this.e[a]={url:b.url,port:b.port}:W(this,a)}};l.Na=function(a){W(this,a.requestId)};
l.J=function(a,b,c,d,e){if(void 0===e&&(this.T=!1,e=new I(this),chrome.app?a=chrome.app.getDetails():chrome.management.get(chrome.i18n.getMessage("@@extension_id"),J(e,0)),chrome.storage?chrome.storage.local.get("version",J(e,1)):window.localStorage&&(b=window.localStorage.getItem("version")||""),chrome.extension.isAllowedIncognitoAccess(J(e,2)),chrome.management.get("jeaohhlajejodfjadcponpnjgkiikocn",J(e,3)),e.c(a,b,c,d,!0)))return;"object"==typeof a&&(a=a.version||"");"object"==typeof d&&(d=d.enabled&&
d.version||"");d&&chrome.management.setEnabled("jeaohhlajejodfjadcponpnjgkiikocn",!1);"object"==typeof b&&(b=b.version||"");a&&a!=b&&null!=b&&(chrome.storage?chrome.storage.local.set({version:a}):window.localStorage.setItem("version",a),d=this.S,d&&b||(a="current="+a,b&&(a+="&previous="+b),c&&(a+="&incognito=1"),d&&(a+="&manager="+d),chrome.tabs.create({url:chrome.extension.getURL("welcome.html?"+a)})))};
l.k=function(a){var b=Array.prototype.slice.call(arguments);this.pa.push(b);a.addListener.apply(a,b.slice(1))};function I(a){this.caller=arguments.callee.caller;this.d=a;this.b=Array.prototype.slice.call(arguments,1);this.a=0}function J(a,b){a.a++;return a.f.bind(a,b)}I.prototype.c=function(){return this.a?(arguments.length&&(this.b=Array.prototype.slice.call(arguments)),!0):!1};I.prototype.f=function(a,b){this.b[a]=b;0==--this.a&&this.caller.apply(this.d,this.b)};
I.prototype.e=function(a,b,c){var d=Array.prototype.slice.call(arguments,3);c&&(d=c.concat(d));a.apply(b,d);this&&0==--this.a&&this.caller.apply(this.d,this.b)};function F(a){var b=Array.prototype.slice.call(arguments,1),c=b[b.length-1];c instanceof I?c.a++:c=null;return I.prototype.e.bind(c,arguments.callee.caller,a,b)}function U(a){var b=a.lastIndexOf("#");return 0>b||b<a.indexOf("?")?a:a.substr(0,b)}function H(a){var b="",c;for(c in a)b&&(b+="; "),b+=a[c].name,b+="=",b+=a[c].value;return b}
function V(a){if(!a||!a.length)return null;for(var b="",c=0;c<a.length;c++)b+=a[c].name,b+=": ",b+=a[c].value,b+="\n";return b}function P(a,b){if(!a)return null;b=b.toLowerCase();for(var c in a)if(a[c].name.toLowerCase()==b)return a[c].value;return null}
function R(a,b){if(!a)return null;b=b.toLowerCase();var c=a.split(";");c.shift();for(var d in c){var e=c[d],f=e.indexOf("=");if(0<f){var g=e.substr(0,f).trim().toLowerCase(),h="*"==g[g.length-1];h&&(g=g.substr(0,g.length-1).trimRight());if(g==b)return c=e.substr(f+1).trim(),d=c.length-1,'"'==c[0]&&'"'==c[d]&&(c=c.substring(1,d)),h&&(c=c.split("'",3).pop()),unescape(c)}else if(0>f&&e.trim().toLowerCase()==b)return""}return null}function Q(a){return a&&unescape(a.split(";",1).shift().trim())||""}
function ka(a,b){if(!a)return null;var c=a.raw;if(c){for(var d=String.fromCharCode,e="",f=0;f<c.length;f++){var g=c[f].bytes;if(!g)return null;for(var g=new Uint8Array(g),h=g.length,k=0;k<h;k++)e+=d(g[k])}return e}c=a.formData;if(!c)return null;f=Q(b).toLowerCase();e=[];if("application/x-www-form-urlencoded"==f)for(d in c)for(g=c[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<g.length;f++)e.length&&e.push("&"),e.push(d,"=",g[f].split(" ").map(encodeURIComponent).join("+"));else if("multipart/form-data"==
f){(h=R(b,"boundary"))||(h="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in c)for(g=c[d],f=0;f<g.length;f++)e.push("--",h,'\r\nContent-Disposition: form-data; name="',d,'"\r\n\r\n',g[f],"\r\n");e.push("--",h,"--\r\n")}else return null;return e.join("")}function T(a){return(a=ca.exec(a))?a[1]:""}function G(a,b){var c=a.split("://",1).shift().toLowerCase(),c=ga[c]||0;return b?c&31:c}function S(a){return(a=ba.exec(a))?a[1]:""}new A;
